### PR TITLE
Add GrowthChart module to the modules reff-app server

### PR DESCRIPTION
**Pull request by mozzy22**

### CODE REVIEW

**Comment by mozzy22** [comment]
@dkayiwa see this Pr. I ddnt want to commit it directly, so i forked it on my other account

**Comment by dkayiwa** [comment]
You may also want to upgrade the modules and platform version to match those on qa-refapp, where in the very first place, they had wanted these changes to be.

**Comment by mozzy22** [comment]
Alright

**Comment by mozzy22** [comment]
can i have some Login Credentials to the server , it seems i cant login with "admin" , "Admin123"

**Comment by dkayiwa** [comment]
sup3rS3cr3tPassw0rd

**Comment by mozzy22** [comment]
i have re-run the deployment on Bamboo , but i cant see yet the growth chart in the server. Any step i have missed ??

**Comment by dkayiwa** [comment]
That is how we used to do it. You can ask Cintia if the process was changed.

**Comment by mozzy11** [comment]
it seems theres a change that was made in the Bamboo deplyment plan , it actally evenhavent updated the docker image here  https://hub.docker.com/layers/openmrs/openmrs-reference-application-distro/modules/images/sha256-62a320ba4082ee87f8fa49b0ba421cfa50a199d2ca4dcbe354eed045e029871a

**Pull request merged**
